@startuml
'https://plantuml.com/class-diagram


class HeroAircraft{
    - {static} heroAircraft
    - shootNum:int
    - power:int
    - direction:int
    - isFiring:boolean;
    - isFiringPlus:boolean;

    + HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + rebuildHeroAircraft();
    + {static} getHeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<BaseBullet>
    + setFiring():boolean
    + closeFiring():boolean
    + setFiringPlus():boolean
    + closeFiringPlus():boolean
    + getDirection():int;
}

HeroAircraft<--HeroAircraft
@enduml